# Configuration file for feature extraction and metric computation
feature_extraction: false
eval_only: false
sing_image_eval: true
realism_correlation: true


# Paths to the real and synthetic datasets
real_dataset_path: './data/real'
synthetic_dataset_path: './data/synthetic/diffusion'

# List of networks to use for feature extraction
networks:
  - 'rad_inception'
  - 'resnet50'
  - 'rad_resnet50'
  - 'inceptionresnet'
  - 'rad_inceptionresnet'
  - 'densenet'
  - 'rad_densenet'
  - 'clip'
  - 'rad_clip'
  - 'rad_dino'
  - 'dino'
  - 'inception'

metrics:
  - fid
  - precision 
  - recall
  - density
  - coverage
  - kid
  - is
  - mmd

# Batch size for feature extraction
batch_size: 64

# Number of sets to divide each dataset into
num_sets: 10

# Directory to save the metrics results
metrics_output_dir: 'metrics'

# Directory to save features and metrics
features_output_dir: 'data/features'

# Path to jsonl where turign test responses are contained
jsonl_path:
- '/home/ksamamov/GitLab/Notebooks/feat_ext_bench/data/turing_tests/evaluations_4e26daae-530d-430b-81be-107704de6a9e_MARC_M.jsonl'
#:- '/home/ksamamov/GitLab/Notebooks/feat_ext_bench/data/turing_tests/evaluations_4e26daae-530d-430b-81be-107704de6a9e_MARC_M.jsonl'
timestamp: '20240822_155631' #'20240821_151647' # for specific features previously computed, use with feature_extraction=false
do_z_score: false

